development:
  adapter: postgresql
  encoding: unicode
  database: smash-tracker_development
  pool: 5
  host: localhost
  username: smash-tracker

test:
  adapter: postgresql
  encoding: unicode
  database: smash-tracker_test
  pool: 5
  host: localhost
  username: smash-tracker
