# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: e1021e7edc5803484077b35405266f78aa75bf19d3fa28aac39d2d1a10ab7fe18c233ca6bd8ee3ca59da96fba8013055923adef8ad48dca5ee2d2214cdf540ea

test:
  secret_key_base: 2b072b6565402e72c507bfc90a807c1a0cd2e08658236add47734590ffa81a8efd05fe57480405432ad97e871aa5500b5476bd99e1965bec3320a8557ea26da8

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
